import libs = libbootstrap%lib{bootstrap}

exe{bootstrap}: {hxx ixx txx cxx}{**} $libs testscript
{
  backlink = true
}

cxx.poptions =+ "-I$out_root" "-I$src_root"
cxx.libs += libnethost/lib/nethost.lib